export const questions = [
  {
    id: "situation",
    question: "Where are you right now?",
    subtitle: "This shapes the entire program around your actual life.",
    type: "single",
    options: [
      { value: "employee", label: "Employee looking to move into leadership", icon: "📈" },
      { value: "leader", label: "Already in leadership — want more authority & respect", icon: "💼" },
      { value: "founder", label: "Entrepreneur or founder building my brand", icon: "🚀" },
      { value: "job_seeker", label: "Job hunting — need to command interviews", icon: "🎯" },
      { value: "professional", label: "Professional who isn't being taken seriously enough", icon: "🔑" },
    ],
  },
  {
    id: "goal",
    question: "What does talking and acting like a CEO mean to you?",
    subtitle: "Pick the outcome that excites you most.",
    type: "single",
    options: [
      { value: "command_room", label: "Walk into any room and immediately command it", icon: "⚡" },
      { value: "respect", label: "Be respected and taken seriously — instantly", icon: "🏆" },
      { value: "pressure", label: "Stay calm, clear, and decisive under pressure", icon: "🧊" },
      { value: "brand", label: "Build a magnetic personal brand and executive presence", icon: "✨" },
      { value: "leadership", label: "Lead, motivate, and move people to action", icon: "🎖️" },
    ],
  },
  {
    id: "challenge",
    question: "What's your biggest communication challenge?",
    subtitle: "Be honest — this is where we focus first.",
    type: "single",
    options: [
      { value: "freeze", label: "I freeze up or lose my train of thought mid-sentence", icon: "🧊" },
      { value: "passive", label: "I'm too quiet — I don't assert my opinions enough", icon: "🤫" },
      { value: "ramble", label: "I ramble and can't get to the point quickly", icon: "💭" },
      { value: "nervous", label: "Nerves show in my body language, voice, or face", icon: "😰" },
      { value: "influence", label: "I struggle to persuade and influence others", icon: "🎭" },
    ],
  },
  {
    id: "arena",
    question: "Where do you need CEO-level confidence most?",
    subtitle: "Choose up to two — your program drills these specifically.",
    type: "multi",
    max: 2,
    options: [
      { value: "meetings", label: "Meetings, boardrooms & high-stakes conversations", icon: "🏛️" },
      { value: "presentations", label: "Presentations & public speaking", icon: "🎤" },
      { value: "authority", label: "One-on-ones with senior leaders or investors", icon: "🤝" },
      { value: "camera", label: "On camera, podcasts, or social media content", icon: "📹" },
      { value: "networking", label: "Networking and making powerful first impressions", icon: "🌐" },
    ],
  },
  {
    id: "self_view",
    question: "How do you see yourself right now?",
    subtitle: "Your honest starting point determines your path.",
    type: "single",
    options: [
      { value: "constant_doubt", label: "I doubt myself constantly — it's exhausting", icon: "😔" },
      { value: "inconsistent", label: "Confident sometimes, but it comes and goes", icon: "🌊" },
      { value: "clear_gaps", label: "Fairly confident but I know my specific gaps", icon: "🔍" },
      { value: "internal_only", label: "Confident inside — just doesn't come across that way", icon: "🔮" },
    ],
  },
  {
    id: "blocker",
    question: "What holds you back most?",
    subtitle: "This is the core we attack in Week 1.",
    type: "single",
    options: [
      { value: "fear_judgment", label: "Fear of judgment or looking stupid", icon: "👁️" },
      { value: "impostor", label: "Imposter syndrome — I feel like I don't belong", icon: "🎭" },
      { value: "no_words", label: "I don't know what to say or how to frame things", icon: "💬" },
      { value: "body_language", label: "My body language gives me away — I look nervous", icon: "🙈" },
      { value: "no_gravitas", label: "I just don't have that 'it factor' or gravitas", icon: "⚖️" },
    ],
  },
  {
    id: "timeline",
    question: "Do you have a high-stakes moment coming up?",
    subtitle: "We'll front-load the most critical skills if you do.",
    type: "single",
    options: [
      { value: "urgent", label: "Yes — within the next 4 weeks", icon: "🔥" },
      { value: "soon", label: "Yes — within the next 3 months", icon: "📅" },
      { value: "ongoing", label: "No specific event — I need this for ongoing situations", icon: "♾️" },
      { value: "identity", label: "I want this as a permanent identity shift", icon: "🌟" },
    ],
  },
  {
    id: "time",
    question: "How much time can you commit each day?",
    subtitle: "Be realistic — consistency beats intensity.",
    type: "single",
    options: [
      { value: "15", label: "15 minutes — busy schedule, need max efficiency", icon: "⏱️" },
      { value: "30", label: "30 minutes — I can make this a daily habit", icon: "⏰" },
      { value: "60", label: "45-60 minutes — I'm serious about fast results", icon: "🎯" },
      { value: "unlimited", label: "As much as it takes — I'm all in", icon: "💪" },
    ],
  },
  {
    id: "learning_style",
    question: "How do you learn and grow best?",
    subtitle: "Your plan's format adapts to how you actually absorb things.",
    type: "single",
    options: [
      { value: "reading", label: "Reading frameworks and deep concepts", icon: "📚" },
      { value: "doing", label: "Jumping in — practice, drills and real exercises", icon: "🏋️" },
      { value: "stories", label: "Learning through examples, stories and models to follow", icon: "🎬" },
      { value: "tracking", label: "Tracking progress, journaling and reflection", icon: "📊" },
    ],
  },
  {
    id: "persona",
    question: "One word: how do you want to be perceived?",
    subtitle: "This becomes your north star identity for the full 12 weeks.",
    type: "single",
    options: [
      { value: "commanding", label: "Commanding — authority no one questions", icon: "👑" },
      { value: "magnetic", label: "Magnetic — people are drawn to you naturally", icon: "🧲" },
      { value: "visionary", label: "Visionary — you see and speak what others can't", icon: "🔭" },
      { value: "trusted", label: "Trusted — the person everyone turns to", icon: "🛡️" },
    ],
  },
];
