export const phases = [
  { number: 1, name: "CEO Foundation", weeks: [1, 2, 3], color: "#c9a84c" },
  { number: 2, name: "Executive Communication", weeks: [4, 5, 6], color: "#4a90d9" },
  { number: 3, name: "Influence & Authority", weeks: [7, 8, 9], color: "#7c4dff" },
  { number: 4, name: "Mastery & Identity", weeks: [10, 11, 12], color: "#00c9a7" },
];

export const weeks = [
  {
    week: 1,
    phase: 1,
    title: "The CEO Identity",
    subtitle: "Decide who you're becoming",
    theme: "Identity",
    icon: "👑",
    principle: "You don't rise to the level of your goals — you fall to the level of your identity. Week 1 is about installing a new one.",
    keySkill: "Identity Architecture",
    days: [
      {
        day: 1,
        focus: "Foundation",
        title: "The Identity Shift",
        description: "CEOs don't act confident — they ARE confident. Learn the difference between doing confidence and being it.",
        exercise: "Write your CEO Identity Statement: 'I am someone who...' Complete it 10 ways. Read it aloud. This is your new operating system.",
        duration: { 15: "Read + write statement", 30: "Read + write + record yourself reading it", 60: "Full exercise + journaling" },
      },
      {
        day: 2,
        focus: "Skill Building",
        title: "How CEOs Think Differently",
        description: "CEOs think in outcomes, not activities. They ask 'what needs to happen?' not 'what should I do?' Learn the 3 cognitive shifts.",
        exercise: "Take 3 decisions you're currently making. Reframe each one from employee-thinking to CEO-thinking using the framework.",
        duration: { 15: "Read the 3 shifts + one reframe", 30: "All 3 reframes written out", 60: "Reframes + identify patterns in your thinking" },
      },
      {
        day: 3,
        focus: "Practice",
        title: "Your CEO Morning Protocol",
        description: "How you start the day sets your identity for the next 16 hours. CEOs don't drift into the day — they enter it intentionally.",
        exercise: "Design your 10-minute CEO morning: 2 min visualization, 3 min affirmations, 5 min review of the day's most important outcome. Do it tomorrow.",
        duration: { 15: "Design + commit", 30: "Design + full first run", 60: "Design + run + refine" },
      },
      {
        day: 4,
        focus: "Challenge",
        title: "Introduce Yourself Like a CEO",
        description: "Most people introduce themselves apologetically. CEOs introduce themselves with clarity and purpose.",
        exercise: "Craft a 15-second introduction that leads with your value, not your title. Use the P-V-A formula: Position + Value + Ask. Practice 5 times today.",
        duration: { 15: "Write it. Say it once.", 30: "Write + say 5x in mirror", 60: "Write + film yourself + review" },
      },
      {
        day: 5,
        focus: "Reflection",
        title: "Week 1 Review: Who Are You Now?",
        description: "Identity doesn't change overnight — but small cracks in the old story make room for the new one.",
        exercise: "Answer: (1) What did you notice about how you see yourself this week? (2) Where did you slip into old patterns? (3) What's the #1 identity belief to reinforce in Week 2?",
        duration: { 15: "Quick 3-question journal", 30: "Full reflection + update your CEO Identity Statement", 60: "Deep journal + plan Week 2 intentionally" },
      },
    ],
    weekChallenge: "Introduce yourself with your new 15-second CEO intro at least once to a real person — colleague, stranger, or on a call.",
    successMetrics: ["You can recite your CEO Identity Statement from memory", "You've completed the morning protocol at least 3 days", "You've delivered your intro at least once"],
  },
  {
    week: 2,
    phase: 1,
    title: "Mastering Your Inner World",
    subtitle: "The mental game behind every great leader",
    theme: "Mindset",
    icon: "🧠",
    principle: "The conversations in your head become the conversations you have with the world. CEOs edit their internal script ruthlessly.",
    keySkill: "Cognitive Reframing",
    days: [
      {
        day: 1,
        focus: "Foundation",
        title: "The CEO Mindset Stack",
        description: "Three beliefs every powerful leader carries: (1) I belong in any room. (2) My perspective has value. (3) Failure is feedback. These aren't affirmations — they're decisions.",
        exercise: "Write down your 3 current core beliefs about yourself as a communicator. Then rewrite each one as a CEO belief. Keep both lists.",
        duration: { 15: "Write current beliefs", 30: "Write + reframe all 3", 60: "Write + reframe + trace where old beliefs came from" },
      },
      {
        day: 2,
        focus: "Skill Building",
        title: "Silencing the Inner Critic",
        description: "The inner critic isn't your enemy — it's a misfiring protection system. Learn to name it, thank it, and dismiss it.",
        exercise: "Name your inner critic. Give it a ridiculous name. When it shows up today, say: '[Name], thanks for your concern. I've got this.' Practice at least 3 times.",
        duration: { 15: "Name + one practice run", 30: "Name + journal its triggers + 3 responses", 60: "Full exercise + map when it shows up most" },
      },
      {
        day: 3,
        focus: "Practice",
        title: "Pressure Inoculation",
        description: "CEOs perform under pressure because they've practiced being uncomfortable. Voluntary discomfort builds the muscle.",
        exercise: "Do one uncomfortable thing today that stretches your comfort zone. Speak up in a meeting, start a conversation, share an opinion. Debrief: what happened?",
        duration: { 15: "Pick + do + one sentence debrief", 30: "Pick + do + full debrief", 60: "Pick + do + deep analysis of your response patterns" },
      },
      {
        day: 4,
        focus: "Challenge",
        title: "The Bold Opinion Exercise",
        description: "CEOs have opinions and voice them. This week's challenge is about standing in your perspective without hedging.",
        exercise: "In your next conversation today, share a direct opinion WITHOUT using: 'I think maybe...', 'I could be wrong but...', or 'Just my opinion.' State it cleanly. Notice the response.",
        duration: { 15: "One instance — go", 30: "Two instances + reflection", 60: "Three instances + track your hedging language patterns" },
      },
      {
        day: 5,
        focus: "Reflection",
        title: "Week 2 Debrief",
        description: "Where is your mind still working against you? The goal isn't to eliminate doubt — it's to act in spite of it.",
        exercise: "Journal: (1) What mindset shift had the biggest impact? (2) When did you catch yourself in old thinking? (3) What's the one belief you need to reinforce most?",
        duration: { 15: "Quick 3-question journal", 30: "Full reflection", 60: "Deep journal + create your personal mindset manifesto" },
      },
    ],
    weekChallenge: "Share a bold, direct opinion — no hedging language — in at least two real conversations this week.",
    successMetrics: ["You can identify your inner critic's trigger patterns", "You've completed at least one voluntary discomfort exercise", "You're catching yourself hedging and stopping mid-sentence"],
  },
  {
    week: 3,
    phase: 1,
    title: "Physical Presence & First Impressions",
    subtitle: "People judge you before you speak",
    theme: "Presence",
    icon: "⚡",
    principle: "55% of your impact is non-verbal. CEOs communicate authority before opening their mouth.",
    keySkill: "Non-Verbal Command",
    days: [
      {
        day: 1,
        focus: "Foundation",
        title: "The Physics of Presence",
        description: "Presence is not mystical — it's physical. Posture, eye contact, stillness, and pace are learnable mechanics.",
        exercise: "Record a 60-second video of yourself talking about anything. Watch it with the sound off. What does your body say? Write 3 things to change.",
        duration: { 15: "Record + quick notes", 30: "Record + full analysis", 60: "Record + analyze + make a second video with corrections" },
      },
      {
        day: 2,
        focus: "Skill Building",
        title: "Power Posture & Space",
        description: "CEOs take up space — physically and psychologically. Collapsing inward signals submission. Expanding signals authority.",
        exercise: "Practice the CEO stance: feet shoulder-width, weight evenly distributed, shoulders back, chin parallel to floor. Hold it for 2 minutes before your next important conversation.",
        duration: { 15: "Practice stance + one application", 30: "Practice + two applications", 60: "Practice + film yourself + full day awareness" },
      },
      {
        day: 3,
        focus: "Practice",
        title: "Eye Contact That Commands",
        description: "Weak eye contact signals insecurity. Dominant eye contact isn't staring — it's presence. The 70/30 rule: hold eye contact 70% while speaking, 100% while listening.",
        exercise: "In every conversation today, practice the 70/30 rule. Notice when you break eye contact and why.",
        duration: { 15: "One full conversation with eye contact awareness", 30: "All conversations — track breaks", 60: "All conversations + debrief patterns" },
      },
      {
        day: 4,
        focus: "Challenge",
        title: "The Stillness Practice",
        description: "Anxious people fidget. CEOs are still. Stillness isn't disengagement — it's control. Practice deliberate stillness today.",
        exercise: "In your next meeting or conversation, notice every fidget impulse. Place your hands flat on the table or in your lap. Don't move unless it's intentional.",
        duration: { 15: "One instance of deliberate stillness", 30: "Entire meeting or two conversations", 60: "Full day practice + debrief" },
      },
      {
        day: 5,
        focus: "Reflection",
        title: "Week 3 Debrief: Your Physical Signature",
        description: "Your non-verbal habits have been wired in for years. One week starts the rewiring — but you have to see the patterns.",
        exercise: "Journal: (1) What's your current strongest non-verbal signal? (2) What's the one physical habit you need to break? (3) Film yourself again — what's changed from Day 1?",
        duration: { 15: "Quick journal + one-minute video", 30: "Full journal + video comparison", 60: "Deep analysis + set Phase 2 intentions" },
      },
    ],
    weekChallenge: "Enter your next high-stakes meeting or conversation using full CEO non-verbals: expanded posture, deliberate eye contact, zero unnecessary movement.",
    successMetrics: ["You've filmed yourself twice and can spot the difference", "You're aware of your fidget triggers", "You've received a comment on your presence or confidence"],
  },
  {
    week: 4,
    phase: 2,
    title: "The Power of Voice & Delivery",
    subtitle: "Your voice is your instrument — learn to play it",
    theme: "Voice",
    icon: "🎤",
    principle: "CEOs don't speak louder — they speak with more intention. Pace, tone, pause, and pitch are leadership tools.",
    keySkill: "Vocal Authority",
    days: [
      {
        day: 1,
        focus: "Foundation",
        title: "The Four Dimensions of Vocal Power",
        description: "Pace (how fast), Volume (how loud), Pitch (how high/low), Pause (the silence). Most people default on all four. CEOs orchestrate all four.",
        exercise: "Record yourself saying: 'The most important thing I want you to know is...' three times — fast/nervous, then normal, then slow/deliberate. Hear the difference.",
        duration: { 15: "Record all 3 + listen", 30: "Record + transcribe what each version communicates", 60: "Record + analyze + practice your target version 5x" },
      },
      {
        day: 2,
        focus: "Skill Building",
        title: "The Power of the Pause",
        description: "Amateurs fill silence. CEOs use it. A 2-second pause before answering adds authority, buys thinking time, and signals you don't need to rush.",
        exercise: "Practice the 2-second pause. When someone asks you a question today — any question — pause 2 seconds before answering. It will feel long. It won't look long.",
        duration: { 15: "Practice in one conversation", 30: "Practice in all conversations", 60: "Practice all day + journal how people responded" },
      },
      {
        day: 3,
        focus: "Practice",
        title: "Dropping Upspeak",
        description: "Upspeak — ending statements as questions? — signals uncertainty? CEOs end statements as statements. Period.",
        exercise: "Record a 2-minute talk about your work. Listen back and mark every time your voice rises at the end of a statement. Practice those sentences again, ending downward.",
        duration: { 15: "Record + identify uptalk moments", 30: "Record + fix top 3 moments", 60: "Full drill until your default changes" },
      },
      {
        day: 4,
        focus: "Challenge",
        title: "Slow Down to Speed Up",
        description: "Fast talking signals anxiety. Slow, deliberate speech signals certainty. The challenge: speak at 80% of your normal speed today.",
        exercise: "All day: speak at 80% pace. Pause between thoughts. Let silence exist. Notice the reactions you get.",
        duration: { 15: "One important conversation at 80%", 30: "Half a day", 60: "Full day + debrief" },
      },
      {
        day: 5,
        focus: "Reflection",
        title: "Week 4 Debrief",
        description: "Your voice has a default setting. This week, you started overriding it.",
        exercise: "Journal: (1) What vocal habit do you lean on most? (2) What happened when you paused deliberately? (3) Record your CEO Identity Statement with full vocal intentionality.",
        duration: { 15: "Quick journal + record statement", 30: "Full journal + recording", 60: "Full analysis + create your vocal goals for Phase 2" },
      },
    ],
    weekChallenge: "Use the deliberate pause in at least 5 real high-stakes moments — meetings, calls, negotiations. Track the outcomes.",
    successMetrics: ["You can hear the difference between your nervous voice and your CEO voice", "You've received feedback that you seem calmer/more authoritative", "You're catching upspeak in real-time"],
  },
  {
    week: 5,
    phase: 2,
    title: "Clarity, Brevity & Impact",
    subtitle: "CEOs say more with less",
    theme: "Communication",
    icon: "🎯",
    principle: "The ability to be clear and brief in the most complex moment is the ultimate leadership communication skill.",
    keySkill: "Executive Clarity",
    days: [
      {
        day: 1,
        focus: "Foundation",
        title: "The BLUF Principle",
        description: "Bottom Line Up Front. CEOs lead with the conclusion, then the evidence. Everyone else buries the point at the end. Change the order — change the impact.",
        exercise: "Think of your last email, message, or conversation. Rewrite it using BLUF: start with the conclusion in one sentence, then add supporting points.",
        duration: { 15: "Rewrite one message", 30: "Rewrite three messages or a conversation script", 60: "Rewrite + practice saying it out loud" },
      },
      {
        day: 2,
        focus: "Skill Building",
        title: "The Rule of Three",
        description: "The human brain processes information best in threes. CEOs don't give five reasons — they give three powerful ones.",
        exercise: "Take any argument, pitch, or explanation you need to make this week. Distill it to exactly three points. Cut the rest.",
        duration: { 15: "One argument → 3 points", 30: "Three arguments → 3 points each", 60: "Create your signature communication frameworks using Rule of 3" },
      },
      {
        day: 3,
        focus: "Practice",
        title: "The 30-Second Answer",
        description: "CEOs answer questions in 30 seconds or less — then stop. Practice the format: Answer + Reason + Example + Return to them.",
        exercise: "For every question you're asked today, answer in 30 seconds using A-R-E. Set a timer if you need to. Notice when you go over.",
        duration: { 15: "One question with timer", 30: "All questions — track time", 60: "Full day practice + analyze your longest answers" },
      },
      {
        day: 4,
        focus: "Challenge",
        title: "Cut the Filler Words",
        description: "'Um,' 'uh,' 'like,' 'you know,' 'basically,' 'kind of' — these are verbal static. CEOs replace filler with silence.",
        exercise: "Record a 3-minute talk about a topic you know well. Count every filler word. Then record it again with pauses instead of fillers. Compare.",
        duration: { 15: "Record + count fillers", 30: "Record + count + re-record without them", 60: "Full drill until your rate drops below 1 filler per minute" },
      },
      {
        day: 5,
        focus: "Reflection",
        title: "Week 5 Debrief",
        description: "Clarity is a discipline, not a talent. Every week you practice it, you get faster and sharper.",
        exercise: "Journal: (1) Where do you still bury the point? (2) What's your most common filler? (3) Write out the 3-point case for your biggest current professional goal.",
        duration: { 15: "Quick journal + 3-point case", 30: "Full journal + 3-point case + practice", 60: "Deep analysis + build your communication system" },
      },
    ],
    weekChallenge: "In your next presentation, proposal, or big conversation — lead with the conclusion first. Every time. Track the reactions.",
    successMetrics: ["You're leading with the point in writing and speech", "Your filler word count has measurably dropped", "People are asking fewer clarifying questions after you speak"],
  },
  {
    week: 6,
    phase: 2,
    title: "Storytelling Like a Leader",
    subtitle: "Data informs. Stories move people.",
    theme: "Storytelling",
    icon: "📖",
    principle: "CEOs don't present facts — they tell stories that make facts matter. The best business communicators are the best storytellers.",
    keySkill: "Narrative Leadership",
    days: [
      {
        day: 1,
        focus: "Foundation",
        title: "Why Stories Beat Data Every Time",
        description: "A story activates 7 areas of the brain. A fact activates 2. CEOs know this intuitively — they wrap every key message in a story.",
        exercise: "Think of a message you need to communicate this week. Write the data version. Then write the story version: someone faced a problem, what happened, what changed.",
        duration: { 15: "Write the story version of one message", 30: "Three messages — data vs story", 60: "Full exercise + identify your top 3 career stories" },
      },
      {
        day: 2,
        focus: "Skill Building",
        title: "The SCR Story Framework",
        description: "Situation → Complication → Resolution. Every great business story follows this arc. It takes 60 seconds to tell — and lands in the listener's memory.",
        exercise: "Tell a story from your professional life using SCR in under 90 seconds. Record it. Did you set up the situation? Introduce real tension? Land a clear resolution?",
        duration: { 15: "Tell one story verbally", 30: "Tell two stories + record one", 60: "Record + critique + re-record improved version" },
      },
      {
        day: 3,
        focus: "Practice",
        title: "Your Signature Stories",
        description: "CEOs have a library of pre-built stories they deploy strategically. Build yours: Leadership story, Challenge story, Vision story, Values story.",
        exercise: "Write out your Leadership Story using SCR — a time you led something through difficulty. Practice telling it in 90 seconds.",
        duration: { 15: "Write the story", 30: "Write + practice out loud 3x", 60: "Write all 4 signature stories" },
      },
      {
        day: 4,
        focus: "Challenge",
        title: "Weave a Story Into a Real Conversation",
        description: "Stories feel risky to use in business because we've been told to 'stay professional.' That belief is costing you influence. Professional IS storytelling.",
        exercise: "In your next meeting or conversation, deliberately use a story to make a point. It can be brief — 30 seconds. Notice how the energy changes.",
        duration: { 15: "One story in one conversation", 30: "One story in each conversation", 60: "Track every story you use + the reactions" },
      },
      {
        day: 5,
        focus: "Reflection",
        title: "Week 6 Debrief",
        description: "You're now halfway through. Phase 3 is about taking everything you've built and making it weaponized for influence.",
        exercise: "Journal: (1) What's your strongest story? (2) Where do you still default to data over story? (3) Craft your 30-second origin story — why you do what you do.",
        duration: { 15: "Quick journal + origin story draft", 30: "Full journal + origin story + practice", 60: "Complete signature story library + midpoint review of full 12 weeks" },
      },
    ],
    weekChallenge: "Tell a story — using the SCR framework — in at least 3 professional conversations this week. No pitch without a story.",
    successMetrics: ["You have at least 3 signature stories you can tell in under 90 seconds", "People are more engaged when you speak", "You've used a story to make a point in a real meeting"],
  },
  {
    week: 7,
    phase: 3,
    title: "Reading the Room",
    subtitle: "Social intelligence is a CEO superpower",
    theme: "Social Intelligence",
    icon: "🧭",
    principle: "The most powerful communicator in any room is rarely the loudest — it's the most aware. CEOs read dynamics and adapt instantly.",
    keySkill: "Social Calibration",
    days: [
      {
        day: 1,
        focus: "Foundation",
        title: "The Room Reading Framework",
        description: "Three things to assess the moment you enter any room: (1) Who has the power? (2) What's the emotional temperature? (3) What does this group need from me right now?",
        exercise: "In your next group setting, assess all three before speaking. Write your observations. Were you right? Did your approach change based on what you read?",
        duration: { 15: "Assess + one-line answer for each", 30: "Assess + full reflection", 60: "Assess + strategy + debrief after" },
      },
      {
        day: 2,
        focus: "Skill Building",
        title: "Active Listening as a Power Move",
        description: "Weak communicators listen to respond. CEOs listen to understand and then respond in a way that makes the speaker feel heard. This builds loyalty.",
        exercise: "In your next conversation, only listen. Ask follow-up questions. Don't offer your opinion or experience. See how long you can go. What do you notice?",
        duration: { 15: "One conversation — just listen", 30: "Two conversations + debrief", 60: "All conversations + identify your listening gaps" },
      },
      {
        day: 3,
        focus: "Practice",
        title: "Mirroring & Matching",
        description: "People trust people who feel like them. Subtle mirroring of tone, pace, and vocabulary creates rapport faster than any tactic.",
        exercise: "In a conversation today, subtly match the other person's pace and energy level — not their exact words. Notice when rapport increases.",
        duration: { 15: "One conversation — try mirroring", 30: "Three conversations + observe rapport shifts", 60: "Full day practice + identify where it feels natural vs forced" },
      },
      {
        day: 4,
        focus: "Challenge",
        title: "The Elephant in the Room",
        description: "CEOs address what everyone's thinking but no one will say. Naming the tension is a power move that instantly positions you as the most self-aware person present.",
        exercise: "In your next group setting, identify the unspoken dynamic and name it. 'I want to acknowledge the tension here...' or 'I think what we're all feeling is...' — and watch what happens.",
        duration: { 15: "Identify + decide if/how to name it", 30: "Name it + reflect on the reaction", 60: "Full practice + build your vocabulary for naming dynamics" },
      },
      {
        day: 5,
        focus: "Reflection",
        title: "Week 7 Debrief",
        description: "Social intelligence is the invisible edge. Most people never develop it consciously — which is why the ones who do seem like naturals.",
        exercise: "Journal: (1) What's the room dynamic you find hardest to read? (2) When do you stop listening and start preparing your response? (3) Where did you feel most socially powerful this week?",
        duration: { 15: "Quick 3-question journal", 30: "Full reflection", 60: "Map your social intelligence strengths and gaps — build a development plan" },
      },
    ],
    weekChallenge: "Go to one group event or meeting this week with the explicit goal of reading the room — not performing in it. Report what you observed.",
    successMetrics: ["You can articulate the power dynamics in your key relationships", "You've caught yourself mid-response-prep and returned to listening", "You've named a tension or dynamic in a group setting"],
  },
  {
    week: 8,
    phase: 3,
    title: "Persuasion & Influence",
    subtitle: "Move people without forcing them",
    theme: "Influence",
    icon: "🎭",
    principle: "CEOs don't convince — they create the conditions for people to convince themselves. Influence is architecture, not pressure.",
    keySkill: "Ethical Persuasion",
    days: [
      {
        day: 1,
        focus: "Foundation",
        title: "The 3 Pillars of CEO Influence",
        description: "Ethos (credibility), Pathos (emotion), Logos (logic). Aristotle cracked this 2,500 years ago. CEOs deploy all three — never just one.",
        exercise: "Take a position you need to persuade someone on. Write out your Ethos argument (why they should trust you), Pathos (what it means for them), and Logos (the logical case).",
        duration: { 15: "One pillar — the one you use least", 30: "All 3 pillars for one argument", 60: "All 3 pillars + practice delivering the full argument" },
      },
      {
        day: 2,
        focus: "Skill Building",
        title: "The Pre-Suasion Frame",
        description: "The most powerful persuasion happens before you make your point. Set the frame — what people notice first shapes everything that follows.",
        exercise: "Before your next pitch, proposal, or argument, set the frame: 'Before I share this, I want you to think about a time when...' Practice this opening today.",
        duration: { 15: "Write your pre-suasion frame", 30: "Write + practice delivering it", 60: "Write + practice + use it in a real conversation" },
      },
      {
        day: 3,
        focus: "Practice",
        title: "Making Them Feel Seen",
        description: "The fastest path to influence is making someone feel deeply understood. Acknowledge before you advocate. It disarms resistance.",
        exercise: "In your next disagreement or resistance moment, lead with: 'I understand why you see it that way... [their view paraphrased]. Here's another angle...' Practice today.",
        duration: { 15: "Write the acknowledge-then-advocate script", 30: "Use it in one real conversation", 60: "Use it in multiple conversations + track how resistance drops" },
      },
      {
        day: 4,
        focus: "Challenge",
        title: "Negotiate Something Today",
        description: "CEOs negotiate everything — not aggressively, but consistently. Scope, timelines, terms, credit. Today's challenge: negotiate something you'd normally just accept.",
        exercise: "Identify one thing you'd normally accept without pushing back on. Negotiate it. Use the 3-pillar approach. Ask for what you want clearly and calmly.",
        duration: { 15: "Identify + write your opening", 30: "Identify + negotiate + debrief", 60: "Negotiate two things + analyze your pattern" },
      },
      {
        day: 5,
        focus: "Reflection",
        title: "Week 8 Debrief",
        description: "Influence is the compounding skill — every conversation you approach as an influence opportunity builds the capability.",
        exercise: "Journal: (1) Which pillar (Ethos/Pathos/Logos) do you over-rely on? (2) When do you give in without advocating for yourself? (3) What's the one influence skill you'll focus on in Week 9?",
        duration: { 15: "Quick 3-question journal", 30: "Full reflection + identify a current high-stakes influence opportunity", 60: "Full analysis + prepare your influence strategy for an upcoming situation" },
      },
    ],
    weekChallenge: "Make a request or negotiation this week that you would normally not make. Use the 3 pillars. Report the outcome.",
    successMetrics: ["You know which persuasion pillar is your strongest and weakest", "You've successfully negotiated something you previously would have accepted", "People have started seeking your opinion more proactively"],
  },
  {
    week: 9,
    phase: 3,
    title: "Performing Under Pressure",
    subtitle: "Grace under fire is the ultimate CEO skill",
    theme: "Pressure",
    icon: "🧊",
    principle: "Pressure doesn't build character — it reveals it. CEOs use pressure as signal, not as threat.",
    keySkill: "Composure & Resilience",
    days: [
      {
        day: 1,
        focus: "Foundation",
        title: "The Physiology of Pressure",
        description: "When pressure hits, your body activates fight-or-flight. CEOs have trained their nervous system to intercept this response before it hijacks their behavior.",
        exercise: "Learn and practice physiological sigh: double inhale through nose + long exhale through mouth. Do it 3 times right now. This is your pattern interrupt.",
        duration: { 15: "Practice 10 times", 30: "Practice + identify your top 3 pressure triggers", 60: "Practice + full nervous system mapping" },
      },
      {
        day: 2,
        focus: "Skill Building",
        title: "Responding vs. Reacting",
        description: "Reaction is automatic. Response is chosen. The gap between stimulus and response is where your leadership lives.",
        exercise: "When you feel triggered or challenged today — pause, breathe, and ask: 'What's the best response here?' Then choose. Track every instance.",
        duration: { 15: "One moment — notice + pause + choose", 30: "All day awareness — track instances", 60: "Full day + analyze your trigger patterns and build response scripts" },
      },
      {
        day: 3,
        focus: "Practice",
        title: "Handling Hostile Questions",
        description: "Hostile questions are designed to throw you off. CEOs turn them into opportunities. Learn the three response moves: Acknowledge, Redirect, Lead.",
        exercise: "Ask a colleague to throw you 3 hard questions about your work. Practice A-R-L on each. Film yourself if possible.",
        duration: { 15: "Write A-R-L for your 3 most feared questions", 30: "Practice with a real person", 60: "Full drill + film + review" },
      },
      {
        day: 4,
        focus: "Challenge",
        title: "Create Pressure Deliberately",
        description: "You can't prepare for pressure in safe environments. Voluntary exposure to discomfort is the only way to expand your capacity.",
        exercise: "Put yourself in a high-stakes situation today: pitch an idea in a meeting, approach someone powerful, make a bold ask. Do the thing that scares you most.",
        duration: { 15: "Identify + commit to doing it", 30: "Do it + debrief immediately after", 60: "Do multiple pressure situations + map your response evolution" },
      },
      {
        day: 5,
        focus: "Reflection",
        title: "Week 9 Debrief",
        description: "Phase 3 is complete. You now have the full toolkit. Phase 4 is about integration — making all of this who you ARE, not just what you do.",
        exercise: "Journal: (1) What's your #1 pressure trigger? (2) What response are you most proud of this week? (3) What does performing under pressure feel like now vs Week 1?",
        duration: { 15: "Quick 3-question journal", 30: "Full reflection + compare to Week 1 answers", 60: "Deep analysis + prepare Phase 4 integration plan" },
      },
    ],
    weekChallenge: "Put yourself in one genuinely high-stakes situation this week — one that scares you. Use your toolkit. Debrief immediately after.",
    successMetrics: ["You can execute the physiological sigh automatically when pressure hits", "You've successfully handled at least one hostile question or challenge", "You're noticing your reaction before it takes over"],
  },
  {
    week: 10,
    phase: 4,
    title: "Your Executive Brand",
    subtitle: "Intentionally shape how the world sees you",
    theme: "Personal Brand",
    icon: "✨",
    principle: "Your reputation is being built whether you're intentional about it or not. CEOs architect their brand deliberately.",
    keySkill: "Brand Architecture",
    days: [
      {
        day: 1,
        focus: "Foundation",
        title: "The Brand Gap",
        description: "The gap between how you see yourself and how others see you is your brand gap. Closing it is the work of executive presence.",
        exercise: "Ask 3 people you trust: 'What are the first 3 words that come to mind when you think of me professionally?' Compare their words to how you want to be perceived.",
        duration: { 15: "Send the 3 messages today", 30: "Ask + reflect on any gaps", 60: "Ask + full brand gap analysis + development plan" },
      },
      {
        day: 2,
        focus: "Skill Building",
        title: "The Three Pillars of Executive Presence",
        description: "Gravitas (how you act), Communication (how you speak), Appearance (how you present yourself). Leaders are judged on all three — simultaneously.",
        exercise: "Rate yourself 1-10 on each pillar. Identify your lowest. Design two specific actions this week to move it up by 1 point.",
        duration: { 15: "Rate + identify lowest", 30: "Rate + two actions", 60: "Full assessment + 30-day action plan" },
      },
      {
        day: 3,
        focus: "Practice",
        title: "Become Quotable",
        description: "CEOs are remembered for what they say. Being quotable isn't luck — it's preparation. Craft your core statements before you need them.",
        exercise: "Write 5 CEO-level statements about your work, values, or vision. Make each one sharp enough to be repeated. Practice saying them until they feel natural.",
        duration: { 15: "Write 3 statements", 30: "Write 5 + practice 3", 60: "Write 5 + practice all + identify where to deploy them" },
      },
      {
        day: 4,
        focus: "Challenge",
        title: "Own Your Narrative",
        description: "If you don't tell your story, others will tell it for you. CEOs control their narrative — in every room, conversation, and introduction.",
        exercise: "Update your professional bio, LinkedIn headline, or email signature to reflect your CEO identity. Make it active, specific, and forward-looking.",
        duration: { 15: "Update one platform", 30: "Update two platforms + review all key touchpoints", 60: "Full audit of your online and in-person brand footprint" },
      },
      {
        day: 5,
        focus: "Reflection",
        title: "Week 10 Debrief",
        description: "Brand is built in the 1,000 small moments no one is tracking. Consistency across those moments is what creates a reputation.",
        exercise: "Journal: (1) What feedback surprised you most from the people you asked? (2) What's the one brand attribute you want to be known for above all else? (3) Where is your brand inconsistent?",
        duration: { 15: "Quick 3-question journal", 30: "Full reflection", 60: "Full analysis + brand consistency audit" },
      },
    ],
    weekChallenge: "Ask 3 people for honest feedback on how they perceive you professionally. Use it to close the brand gap.",
    successMetrics: ["You've received external feedback on your professional brand", "Your online presence reflects your CEO identity", "You have 5 quotable statements you can deploy naturally"],
  },
  {
    week: 11,
    phase: 4,
    title: "Advanced Presence & Gravitas",
    subtitle: "The intangibles that make leaders unforgettable",
    theme: "Gravitas",
    icon: "🏔️",
    principle: "Gravitas isn't a character trait — it's a cultivated combination of substance, composure, and the ability to make others feel important.",
    keySkill: "Commanding Gravitas",
    days: [
      {
        day: 1,
        focus: "Foundation",
        title: "What Gravitas Actually Is",
        description: "Gravitas is the quality that makes people lean in when you speak, remember what you said, and think of you when high-stakes decisions are made.",
        exercise: "Think of someone you consider to have gravitas. List 10 specific behaviors that create that impression. Which of those do you already have? Which are gaps?",
        duration: { 15: "List 10 + quick gap analysis", 30: "List + detailed gap analysis", 60: "Full analysis + behavior modeling plan" },
      },
      {
        day: 2,
        focus: "Skill Building",
        title: "Saying Less, Meaning More",
        description: "Gravitas requires restraint. The most powerful people in any room speak the least and are heard the most. Practice strategic brevity.",
        exercise: "In every meeting or conversation today, say 30% less than you normally would. Choose only your highest-value contributions. Track what happens.",
        duration: { 15: "One meeting — 30% less", 30: "Half a day", 60: "Full day + log your highest-value contributions" },
      },
      {
        day: 3,
        focus: "Practice",
        title: "The Art of the Powerful Question",
        description: "CEOs move conversations forward with questions, not statements. A powerful question changes how people think. It's a form of leadership.",
        exercise: "In your next three conversations, ask at least one question that opens thinking rather than closes it. Not 'did you do X?' but 'what would it take to...' or 'what's the most important thing here?'",
        duration: { 15: "One powerful question in one conversation", 30: "Three conversations with intentional questions", 60: "Build a personal library of powerful questions" },
      },
      {
        day: 4,
        focus: "Challenge",
        title: "Receive Feedback Like a CEO",
        description: "How you receive criticism is a leadership signal. CEOs don't get defensive — they get curious. Defensiveness is a credibility killer.",
        exercise: "Seek out one piece of critical feedback today. Receive it with: 'That's helpful — tell me more about that.' No defending, no explaining. Just listening and asking.",
        duration: { 15: "Seek + receive one piece", 30: "Seek + receive + reflect on your instinct to defend", 60: "Full exercise + analyze your feedback patterns" },
      },
      {
        day: 5,
        focus: "Reflection",
        title: "Week 11 Debrief",
        description: "You're one week from the finish. What you've built over these 11 weeks isn't a skill set — it's an identity.",
        exercise: "Journal: (1) What does gravitas feel like when you have it? (2) When do you still lose it? (3) Write a letter from your future self — the person who fully embodies this identity — to yourself today.",
        duration: { 15: "Quick journal + one paragraph from future self", 30: "Full journal + full letter from future self", 60: "Full reflection + Week 12 preparation" },
      },
    ],
    weekChallenge: "Seek out critical feedback from someone you respect. Receive it with curiosity, not defense. Let it land.",
    successMetrics: ["People are treating you differently — with more deference or attention", "You're speaking less and being heard more", "You've successfully received difficult feedback without becoming defensive"],
  },
  {
    week: 12,
    phase: 4,
    title: "Integration & CEO Identity",
    subtitle: "You don't finish the program — you become the program",
    theme: "Integration",
    icon: "🌟",
    principle: "The goal was never to 'be more confident.' It was to become someone for whom confidence is the baseline.",
    keySkill: "Identity Integration",
    days: [
      {
        day: 1,
        focus: "Foundation",
        title: "The Full Journey",
        description: "Week 1 you declared an identity. Weeks 2-11 you built the evidence for it. Today you look at all of it and own it.",
        exercise: "Go back and read your Week 1 CEO Identity Statement. Write a new one. Compare them. What's different? This gap is 11 weeks of real growth.",
        duration: { 15: "Read + new statement", 30: "Read + new statement + compare", 60: "Full journey reflection + comprehensive new statement" },
      },
      {
        day: 2,
        focus: "Skill Building",
        title: "Your CEO Playbook",
        description: "Great leaders have systems — not just skills. Codify what you've learned into a personal playbook you can return to.",
        exercise: "Write your CEO Playbook: your top 3 principles, 3 communication non-negotiables, 3 pressure-management tools, and 3 identity anchors.",
        duration: { 15: "One section of the playbook", 30: "Full playbook — rough draft", 60: "Complete, polished CEO Playbook" },
      },
      {
        day: 3,
        focus: "Practice",
        title: "The Capstone Performance",
        description: "Put everything to work in one high-stakes moment. Choose your biggest upcoming opportunity and execute with full CEO presence.",
        exercise: "Identify one high-stakes moment this week — a presentation, meeting, conversation, or pitch. Prepare using everything you've learned. Execute. Film it if possible.",
        duration: { 15: "Identify + prepare mentally", 30: "Identify + prepare fully", 60: "Identify + prepare + film + review" },
      },
      {
        day: 4,
        focus: "Challenge",
        title: "Share What You've Learned",
        description: "Teaching solidifies mastery. You now have 12 weeks of hard-won insight. Share one lesson with someone who could benefit.",
        exercise: "Have a conversation with someone about one thing you've learned in this program. Teach it as if you're the expert — because now you are.",
        duration: { 15: "Share one insight", 30: "Full 10-minute conversation about your journey", 60: "Write a reflection you could share publicly" },
      },
      {
        day: 5,
        focus: "Reflection",
        title: "The Beginning",
        description: "This isn't the end. It's the new baseline.",
        exercise: "Final journal: (1) How are you different from the person who started Week 1? (2) What's the single biggest identity shift you've made? (3) What's the commitment you're making to sustain this? Write it. Sign it.",
        duration: { 15: "Quick final journal", 30: "Full final reflection", 60: "Complete journal + public declaration + next chapter planning" },
      },
    ],
    weekChallenge: "Deliver your capstone performance — one high-stakes moment where you bring everything. This is what you trained for.",
    successMetrics: ["Your new CEO Identity Statement sounds nothing like the first one", "You have a CEO Playbook you'll actually use", "You feel like a fundamentally different communicator than you did 12 weeks ago"],
  },
];
